#!/usr/bin/env node

var colors = require("colors");

var glace = require("../../lib");

glace.config.isWeb = true;

glace.run().then(errCode => {
    if (!errCode) {
        console.log("It's passed! 🙂".green.bold);
    } else {
        console.log("It's failed! 🙁".red.bold);
    };
    process.exit(errCode);
});
